# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread_data',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='thread_data',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
