# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20170205_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread_data',
            name='author',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='thread_data',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
