# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20170205_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_data',
            name='author_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='message_data',
            name='author_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
