# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_announcements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_announcements',
            old_name='subject',
            new_name='class_id',
        ),
    ]
