# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_announcements',
            name='author',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='class_announcements',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='class_assignments',
            name='author',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='class_assignments',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
