# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_data',
            name='password',
        ),
        migrations.AddField(
            model_name='teachers_data',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teachers_data',
            name='mobile',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
