# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20170204_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers_data',
            name='otp',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
