# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20170204_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects_assignments',
            name='subject',
        ),
        migrations.DeleteModel(
            name='subjects_assignments',
        ),
    ]
